Create usePermissions hook
CEIP-USP/frontend pull request #11
Opened 2021-12-02 21:03 UTC by T-Guerrero

Squashed commit of the following:

commit 9004249a44b5656c405c4a8da4af77be50574392
Author: Vinicius Frota <viniciuspxfrota@gmail.com>
Date:   Thu Dec 2 18:01:20 2021 -0300

    mob next

Signed-off-by: Vinicius Frota <viniciuspxfrota@gmail.com>
Co-authored-by: Thiago Guerrero <tgbalera@hotmail.com>

2021-12-07 12:40 UTC, jooaodanieel commented on src/hooks/Permissions.ts
> +};
[Apenas um comentário, não chega a ser um pedido de mudança]

Aqui ficaria legal o uso de um Builder ein

2021-12-07 12:49 UTC, jooaodanieel requested changes

2021-12-07 12:49 UTC, jooaodanieel commented on src/hooks/Permissions.ts
> +  }
Fiquei confuso com relação ao nome dessa função. Acho que fica melhor algo como `getPermittedLinks` ou `getAllowedLinks` -- `process` dá a entender vai receber uma lista de TypeLink e devolver outra, sem contar que é meio genérico.

2021-12-07 12:49 UTC, jooaodanieel commented on src/pages/Search.tsx
> +      <AccessControl roles={['User']}>
[Dúvida] O uso das duas tags aqui não é redundante? Digo no sentido de que o `AccessControl` verifica se está logado para poder autorizar o componente.

2021-12-07 19:42 UTC, T-Guerrero commented on src/hooks/Permissions.ts
> +  }
o nome `process` veio do fato que vamos ter que processar para tirar as duplicações quando for possível mais de um cargo

2021-12-07 19:44 UTC, T-Guerrero commented on src/pages/Search.tsx
> +      <AccessControl roles={['User']}>
Não exatamente, o `requireAuthN` tenta relogar caso não esteja logado. Acho que é bom deixar separado pra entender que são duas camadas diferentes (mesmo que em algum momento tenha uma redundância)

2021-12-07 20:03 UTC, jooaodanieel commented on src/hooks/Permissions.ts
> +  }
Então o nome de agora é referente a algo que virá no futuro? 🕐 
Continuo achando que o nome dessa função deveria ser algo como `getAllowedLinks` -- e num futuro ter uma subrotina de processamento para remover duplicatas

2021-12-08 13:55 UTC, jooaodanieel approved these changes

2021-12-09 00:00 UTC, merged