Integrate/many roles
CEIP-USP/frontend pull request #14
Opened 2021-12-14 02:25 UTC by T-Guerrero

2021-12-14 21:21 UTC, jooaodanieel requested changes

2021-12-14 21:21 UTC, jooaodanieel commented on src/hooks/Permissions.ts
> +    if (!isAuthenticated || !roles) return [];
Pensando aqui, o caso de ser do cargo "Usuário" não deveria ter `[]` também? (to com feeling de que to falando merda, tho)

2021-12-14 21:21 UTC, jooaodanieel commented on src/hooks/Profile.ts
> +  };
Esse hardcoded deveria ter sido apagado?

2021-12-14 21:21 UTC, jooaodanieel commented on src/pages/EditProfile.tsx
> +      const profileData = await http.get('/profiles', profile._id);
Esse `const profileData = ` tá quebrando o build, porque a variável tá sem uso. Nesse caso, acho melhor fazer a linha 35 ser apenas `await http.get('/profiles', profile._id)` -- a variável passa a ser craida quando houver o resto do código.

2021-12-14 22:11 UTC, T-Guerrero commented on src/hooks/Permissions.ts
> +    if (!isAuthenticated || !roles) return [];
Nop, usuário pode ver o próprio perfil

2021-12-17 14:43 UTC, jooaodanieel approved these changes

2021-12-17 15:00 UTC, merged